include(
    ":Feature:Genius:GeniusApi",
    ":Feature:Genius:GeniusImpl",
    ":Feature:Spotify:spotify-app-remote",
    ":Feature:Spotify:SpotifyApi",
    ":Feature:Spotify:SpotifyImpl",
    ":Feature:Spotify:SpotifyCommon",
    ":Feature:Suggestion"
)